[package]
name = "aws-sigv4"
version = "0.0.23-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "David Barsky <me@davidbarsky.com>"]
description = "SigV4 signer for HTTP requests and Event Stream messages."
edition = "2018"
exclude = ["aws-sig-v4-test-suite/*"]
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
sign-http = ["http", "percent-encoding", "form_urlencoded"]
sign-eventstream = ["aws-smithy-eventstream", "bytes"]
default = ["sign-http"]

[dependencies]
aws-smithy-eventstream = { path = "../aws-smithy-eventstream", optional = true }
bytes = { version = "1", optional = true }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
form_urlencoded = { version = "1.0", optional = true }
hex = "0.4"
http = { version = "0.2", optional = true }
once_cell = "1.8"
percent-encoding = { version = "2.1", optional = true }
regex = "1.5"
ring = "0.16"
tracing = "0.1"

[dev-dependencies]
bytes = "1"
httparse = "1.5"
pretty_assertions = "1.0"
proptest = "1"