[package]
name = "aws-smithy-http-auth"
version = "0.58.0"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
  "Eduardo Rodrigues <16357187+eduardomourar@users.noreply.github.com>",
]
description = "This crate is no longer used by smithy-rs and is deprecated."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"

[dependencies]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata