[[bin]]
name = "tls"
path = "src/main.rs"

[package]
name = "tls"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
name = "tls"
path = "src/lib.rs"

[dependencies]
webpki-roots = "0.22.2"
rustls = "0.20.2"

[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.14.0"

[dependencies.aws-smithy-client]
path = "../../sdk/aws-smithy-client"
version = "0.44.0"

[dependencies.aws-sdk-kms]
default-features = false
path = "../../sdk/kms"
version = "0.14.0"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.hyper-rustls]
version = "0.23.0"
features = ["http2"]
