[package]
name = "setting-timeouts"
version = "0.1.0"
authors = ["Zelda Hessler zhessler@amazon.com>"]
edition = "2018"
publish = false
[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.49.0"

[dependencies.aws-sdk-s3]
path = "../../sdk/s3"
version = "0.19.0"

[dependencies.aws-smithy-client]
features = ["rustls"]
path = "../../sdk/aws-smithy-client"
version = "0.49.0"

[dependencies.aws-smithy-types]
path = "../../sdk/aws-smithy-types"
version = "0.49.0"

[dependencies.tokio]
version = "1.20.1"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.15"
features = ["env-filter"]
