[package]
name = "custom-retries-examples"
version = "0.1.0"
authors = ["John DiSanti <jdisanti@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2021"
publish = false

[dependencies]
lazy_static = "1.4.0"
async_once = "0.2.6"
tracing = "0.1.37"

[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.53.0"

[dependencies.aws-sdk-s3]
path = "../../sdk/s3"
version = "0.23.0"

[dependencies.aws-smithy-client]
features = ["rustls"]
path = "../../sdk/aws-smithy-client"
version = "0.53.0"

[dependencies.aws-smithy-types]
path = "../../sdk/aws-smithy-types"
version = "0.53.0"

[dependencies.tokio]
version = "1.20.1"
features = ["full"]

[dependencies.structopt]
version = "0.3"
default-features = false

[dependencies.tracing-subscriber]
version = "0.3.15"
features = ["env-filter"]
