[package]
name = "s3-helloworld"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
s3 = { package = "aws-sdk-s3", path = "../../s3" }
smithy-http = { path = "../../smithy-http" }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2.18"

[profile.dev]
split-debuginfo = "unpacked"
