[package]
name = "sdk-examples-test-utils"
version = "0.1.0"
authors = ["David Souther <dpsouth@amazon.com>"]
edition = "2021"
publish = false

[dependencies]
http = "0.2"

[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.53.1"

[dependencies.aws-smithy-client]
features = ["test-util"]
path = "../../sdk/aws-smithy-client"
version = "0.53.1"

[dependencies.aws-smithy-http]
path = "../../sdk/aws-smithy-http"
version = "0.53.1"

[dependencies.aws-types]
path = "../../sdk/aws-types"
version = "0.53.1"

[lib]
path = "src/mod.rs"
