[package]
name = "aws-types"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
tracing = "0.1"

[dev-dependencies]
tracing-test = "0.1.0"
serde = { version = "1", features = ["derive"]}
serde_json = "1"
arbitrary = "1"
futures-util = "0.3.16"

[build-dependencies]
rustc_version = "0.4.0"
