[package]
name = "aws-hyper"
version = "0.0.23-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "AWS SDK Tower middleware stack."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
default = []
native-tls = ["hyper-tls", "aws-smithy-client/native-tls"]
rustls = ["hyper-rustls", "aws-smithy-client/rustls"]

[dependencies]
aws-endpoint = { path = "../aws-endpoint" }
aws-http = { path = "../aws-http" }
aws-sig-auth = { path = "../aws-sig-auth" }
aws-smithy-client = { path = "../aws-smithy-client" }
aws-smithy-http = { path = "../aws-smithy-http" }
aws-smithy-http-tower = { path = "../aws-smithy-http-tower" }
aws-smithy-types = { path = "../aws-smithy-types" }
bytes = "1"
fastrand = "1.4.0"
http = "0.2.3"
http-body = "0.4.0"
hyper = { version = "0.14.2", features = ["client", "http1", "http2", "tcp", "runtime"] }
hyper-rustls = { version = "0.22.1", optional = true, features = ["rustls-native-certs"] }
hyper-tls = { version ="0.5.0", optional = true }
tokio = { version = "1", features = ["time"] }
tower = { version = "0.4.6", features = ["util", "retry"] }

pin-project = "1"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
tower-test = "0.4.0"
aws-types = { path = "../aws-types" }
aws-smithy-client = { path = "../aws-smithy-client", features = ["test-util"] }

[[test]]
name = "e2e_test"