[package]
name = "aws-hyper"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test-util = ["protocol-test-helpers"]
default = ["test-util"]

[dependencies]
hyper = { version = "0.14.2", features = ["client", "http1", "http2", "tcp", "runtime"] }
tower = { version = "0.4.6", features = ["util", "retry"] }
hyper-tls = "0.5.0"
aws-auth = { path = "../aws-auth" }
aws-sig-auth = { path = "../aws-sig-auth" }
aws-endpoint = { path = "../aws-endpoint" }
aws-http = { path = "../aws-http" }
http = "0.2.3"
bytes = "1"
http-body = "0.4.0"
smithy-http = { path = "../smithy-http" }
smithy-types = { path = "../smithy-types" }
smithy-http-tower = { path = "../smithy-http-tower" }
fastrand = "1.4.0"
tokio = { version = "1", features = ["time"] }

pin-project = "1"
tracing = "0.1.25"

protocol-test-helpers = { path = "../protocol-test-helpers", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
tower-test = "0.4.0"
aws-types = { path = "../aws-types" }

[[test]]
name = "e2e_test"
required-features = ["test-util"]
