[package]
name = "aws-smithy-types"
version = "0.0.0-smithy-rs-head"
authors = [
    "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
    "Russell Cohen <rcoh@amazon.com>",
]
description = "Types for smithy-rs codegen."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
test-util = []
serde-serialize = []
serde-deserialize = []

[dependencies]
base64-simd = "0.8"
itoa = "1.0.0"
num-integer = "0.1.44"
ryu = "1.0.5"
time = { version = "0.3.4", features = ["parsing"] }

[dev-dependencies]
base64 = "0.13.0"
ciborium = { version = "0.2.1" }
criterion = "0.4"
lazy_static = "1.4"
proptest = "1"
rand = "0.8.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata

[[bench]]
name = "base64"
harness = false

[target."cfg(aws_sdk_unstable)".dependencies.serde]
version = "1"
features = ["derive"]