[package]
name = "aws-smithy-query"
version = "0.27.0-alpha.1"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
description = "AWSQuery and EC2Query Smithy protocol logic for smithy-rs."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-types = { path = "../aws-smithy-types" }
urlencoding = "1.3"