[package]
name = "step-function-code-examples"
version = "0.1.0"
authors = ["Daniele Frasca <https://github.com/ymwjbxxq/>"]
edition = "2021"
publish = false
[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.0.0-smithy-rs-head"

[dependencies.aws-sdk-sfn]
path = "../../sdk/sfn"
version = "0.45.0"

[dependencies.tokio]
version = "1.20.1"
features = ["full"]

[dependencies.structopt]
version = "0.3"
default-features = false

[dependencies.tracing-subscriber]
version = "0.3.15"
features = ["env-filter"]
