[package]
name = "aws-http"
version = "0.0.23-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "HTTP specific AWS SDK behaviors."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-http = { path = "../aws-smithy-http" }
aws-smithy-types = { path = "../aws-smithy-types" }
aws-types = { path = "../aws-types" }
http = "0.2.3"
lazy_static = "1"
thiserror = "1"
tracing = "0.1"

[dev-dependencies]
async-trait = "0.1.50"
aws-smithy-async = { path = "../aws-smithy-async", features = ["rt-tokio"] }
env_logger = "0.9"
http = "0.2.3"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "test-util"] }
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }