[package]
name = "smithy-http-tower"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"
description = "Tower compatible shims for Smithy middleware"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithy-http = { path = "../smithy-http" }
tower = { version = "0.4.4" }
pin-project = "1"
http = "0.2.3"
bytes = "1"
http-body = "0.4.0"
tracing = "0.1.24"

[dev-dependencies]
tower = { version = "0.4.4", features = ["util"] }
tokio = { version = "1", features = ["full"]}
