[package]
name = "aws-smithy-http"
version = "0.27.0-alpha.1"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "Smithy HTTP logic for smithy-rs."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
bytestream-util = ["tokio/fs", "tokio-util/io"]
event-stream = ["aws-smithy-eventstream"]
default = ["bytestream-util"]

[dependencies]
aws-smithy-eventstream = { path = "../aws-smithy-eventstream", optional = true }
aws-smithy-types = { path = "../aws-smithy-types" }
bytes = "1"
bytes-utils = "0.1"
http = "0.2.3"
http-body = "0.4.0"
percent-encoding = "2.1.0"
pin-project = "1"
thiserror = "1"
tracing = "0.1"

# We are using hyper for our streaming body implementation, but this is an internal detail.
hyper = "0.14.5"

# ByteStream internals
futures-core = "0.3.14"
tokio = { version = "1.6", optional = true }
tokio-util = { version = "0.6", optional = true}

[dev-dependencies]
async-stream = "0.3"
futures-util = "0.3"
hyper = { version = "0.14.5", features = ["stream"] }
proptest = "1"
tokio = {version = "1.6", features = ["macros", "rt", "rt-multi-thread", "fs", "io-util"]}
tokio-stream = "0.1.5"
tempfile = "3.2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]