[package]
name = "aws-smithy-eventstream"
version = "0.27.0-alpha.1"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
description = "Event stream logic for smithy-rs."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
derive-arbitrary = ["arbitrary"]
default = []

[dependencies]
arbitrary = { version = "1", optional = true, features = ["derive"] }
aws-smithy-types = { path = "../aws-smithy-types" }
bytes = "1"
crc32fast = "1"

[dev-dependencies]
bytes-utils = "0.1"