[package]
name = "using-native-tls-instead-of-rustls"
version = "0.1.0"
authors = ["Zelda Hessler zhessler@amazon.com>"]
edition = "2018"
publish = false
[dependencies.aws-config]
features = ["native-tls", "rt-tokio"]
default-features = false
path = "../../sdk/aws-config"
version = "0.14.0"

[dependencies.aws-sdk-s3]
features = ["native-tls"]
default-features = false
path = "../../sdk/s3"
version = "0.14.0"

[dependencies.aws-sdk-sts]
features = ["native-tls"]
default-features = false
path = "../../sdk/sts"
version = "0.14.0"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.5"
features = ["env-filter"]
