[package]
name = "qldbsession-helloworld"
version = "0.1.0"
authors = ["Russell Cohen <rcoh@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qldbsession = { package = "aws-sdk-qldbsession", path = "../../qldbsession" }
### To use native TLS:
# dynamodb = { package = "aws-sdk-qldbsession", path = "../../qldbsession", default-features = false, features = ["native-tls"] }

tokio = { version = "1", features = ["full"] }

# used only for static endpoint configuration:
http = "0.2.3"

# used only to enable basic logging:
env_logger = "0.8.2"
