[package]
name = "sending-presinged-requests"
version = "0.1.0"
authors = ["Zelda Hessler <zhessler@amazon.com>"]
edition = "2018"
publish = false

[dependencies]
http = "0.2.6"
hyper = "0.14"
reqwest = "0.11"

[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.14.0"

[dependencies.aws-sdk-s3]
path = "../../sdk/s3"
version = "0.14.0"

[dependencies.aws-smithy-client]
path = "../../sdk/aws-smithy-client"
version = "0.44.0"

[dependencies.structopt]
version = "0.3"
default-features = false

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.5"
features = ["env-filter"]
