[package]
name = "aws-sig-auth"
version = "0.0.23-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "SigV4 signing middleware for the AWS SDK."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
sign-eventstream = ["aws-smithy-eventstream", "aws-sigv4/sign-eventstream"]
default = []

[dependencies]
aws-sigv4 = { path = "../aws-sigv4" }
aws-smithy-eventstream = { path = "../aws-smithy-eventstream", optional = true }
aws-smithy-http = { path = "../aws-smithy-http" }
aws-types = { path = "../aws-types" }
http = "0.2.2"
# Trying this out as an experiment. thiserror can be removed and replaced with hand written error
# implementations and it is not a breaking change.
thiserror = "1"
tracing = "0.1"

[dev-dependencies]
aws-endpoint = { path = "../aws-endpoint" }
tracing-test = "0.1"