allowed_external_types = [
    "aws_credential_types::credentials_impl::Credentials",
    "aws_sigv4::http_request::sign::SignableBody",
    "aws_sigv4::http_request::error::SigningError",
    "aws_smithy_http::*",
    "aws_smithy_types::body::SdkBody",
    "aws_types::*",
    "http::request::Request",
    "aws_smithy_runtime_api::client::identity::Identity",

    # TODO(https://github.com/smithy-lang/smithy-rs/issues/1193): Once tooling permits it, only allow the following types in the `event-stream` feature
    "aws_smithy_eventstream::frame::SignMessage",
]
