[package]
name = "aws-smithy-protocol-test"
version = "0.0.0-smithy-rs-head"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "A collection of library functions to validate HTTP requests against Smithy protocol tests."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
http = "0.2.1"
thiserror = "1"
serde_json = "1"
regex = "1.5"
# Not perfect for our needs, but good for now
assert-json-diff = "1.1"

pretty_assertions = "1.3"
roxmltree = "0.14.1"


[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata