[package]
name = "aws-config"
version = "0.0.23-alpha"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "AWS SDK config and credential provider implementations."
edition = "2018"
exclude = ["test-data/*", "integration-tests/*"]
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[features]
default-provider = ["profile", "imds", "meta", "sts", "environment", "http-provider"]
profile = ["sts", "web-identity-token", "meta", "environment", "imds", "http-provider"]
meta = ["tokio/sync"]
imds = ["profile", "aws-smithy-http", "aws-smithy-http-tower", "aws-smithy-json", "tower", "aws-http", "meta"]
environment = ["meta"]
sts = ["aws-sdk-sts", "aws-hyper"]
web-identity-token = ["sts", "profile"]
http-provider = ["aws-hyper", "aws-smithy-json", "aws-smithy-http", "tower", "tokio/sync"]
tcp-connector = ["tokio/net", "tower"]

# SSO is not supported
sso = []

rustls = ["aws-smithy-client/rustls"]
native-tls = ["aws-smithy-client/native-tls"]
rt-tokio = ["aws-smithy-async/rt-tokio"]

# Tokio based DNS-resolver for ECS validation
dns = ["tokio/rt"]

default = ["default-provider", "rustls", "rt-tokio", "dns", "tcp-connector"]

[dependencies]
aws-sdk-sts = { path = "../sts", optional = true }
aws-smithy-async = { path = "../aws-smithy-async" }
aws-smithy-client = { path = "../aws-smithy-client" }
aws-smithy-types = { path = "../aws-smithy-types" }
aws-types = { path = "../aws-types" }
tokio = { version = "1", features = ["sync"], optional = true }
tracing = { version = "0.1" }

# TODO: remove when middleware stacks are moved inside of clients directly
aws-hyper = { path = "../aws-hyper", optional = true }

# imds
aws-http = { path = "../aws-http", optional = true }
aws-smithy-http = { path = "../aws-smithy-http", optional = true }
aws-smithy-http-tower = { path = "../aws-smithy-http-tower", optional = true }
aws-smithy-json = { path = "../aws-smithy-json", optional = true }
bytes = "1.1.0"
http = "0.2.4"
tower = { version = "0.4.8", optional = true }

[dev-dependencies]
futures-util = "0.3.16"
tracing-test = "0.1.0"

tokio = { version = "1", features = ["full"] }
# used to test compatibility
async-trait = "0.1.51"
env_logger = "0.9.0"

# used for fuzzing profile parsing
arbitrary = "1.0.2"

# used for test case deserialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

aws-smithy-client = { path = "../aws-smithy-client", features = ["test-util"] }