# IMPORTANT: Types from `aws-sdk-*` crates MUST NOT be allowed to be
# exposed in `aws-config`'s public API. Otherwise, `aws-config` will
# require manual version bumping every time an automated version bump
# to the exposed SDK crates happens.
allowed_external_types = [
   "aws_credential_types::cache::CredentialsCache",
   "aws_credential_types::provider::ProvideCredentials",
   "aws_credential_types::provider::Result",
   "aws_credential_types::provider::SharedCredentialsProvider",
   "aws_sdk_sts::types::_policy_descriptor_type::PolicyDescriptorType",
   "aws_smithy_async::rt::sleep::AsyncSleep",
   "aws_smithy_async::rt::sleep::SharedAsyncSleep",
   "aws_smithy_async::time::SharedTimeSource",
   "aws_smithy_async::time::TimeSource",
   "aws_smithy_http::endpoint",
   "aws_smithy_http::endpoint::error::InvalidEndpointError",
   "aws_smithy_runtime::client::identity::cache::IdentityCache",
   "aws_smithy_runtime::client::identity::cache::lazy::LazyCacheBuilder",
   "aws_smithy_runtime_api::client::dns::ResolveDns",
   "aws_smithy_runtime_api::client::dns::SharedDnsResolver",
   "aws_smithy_runtime_api::client::http::HttpClient",
   "aws_smithy_runtime_api::client::http::SharedHttpClient",
   "aws_smithy_runtime_api::client::identity::ResolveCachedIdentity",
   "aws_smithy_runtime_api::client::identity::ResolveIdentity",
   "aws_smithy_runtime_api::client::behavior_version::BehaviorVersion",
   "aws_smithy_runtime_api::client::orchestrator::HttpResponse",
   "aws_smithy_runtime_api::client::result::SdkError",
   "aws_smithy_types::body::SdkBody",
   "aws_smithy_types::retry",
   "aws_smithy_types::retry::*",
   "aws_smithy_types::timeout",
   "aws_smithy_types::timeout::OperationTimeoutConfig",
   "aws_smithy_types::timeout::TimeoutConfig",
   "aws_smithy_types::timeout::TimeoutConfigBuilder",
   "aws_types::*",
   "http::response::Response",
   "http::uri::Uri",
   "tower_service::Service",

   # TODO(https://github.com/smithy-lang/smithy-rs/issues/1193): Decide if the following should be exposed
   "hyper::client::connect::Connection",
   "tokio::io::async_read::AsyncRead",
   "tokio::io::async_write::AsyncWrite",
]
