[package]
name = "aws-smithy-json-fuzz"
version = "0.0.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
aws-smithy-json = { path = ".." }
aws-smithy-types = { path = "../../aws-smithy-types" }
libfuzzer-sys = "0.4"
serde_json = { version = "1", features = ["float_roundtrip"] }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "json_deserialize"
path = "fuzz_targets/json_deserialize.rs"
test = false
doc = false

[[bin]]
name = "json_deserialize_corpus_cov"
path = "fuzz_targets/json_deserialize_corpus_cov.rs"
test = false
doc = false
