[package]
name = "secretsmanager-code-examples"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"
description = "Example usage of the SecretManager service"

[dependencies]
aws-config = { path = "../../sdk/aws-config" }
secretsmanager = { package = "aws-sdk-secretsmanager", path = "../../sdk/secretsmanager" }
aws-hyper = { path = "../../sdk/aws-hyper" }
aws-types = { path = "../../sdk/aws-types" }

tokio = { version = "1", features = ["full"]}

structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.2.16", features = ["fmt"] }
