[package]
name = "aws-smithy-http-tower"
version = "0.27.0-alpha.1"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "Tower-compatible shims for smithy-rs middleware."
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-http = { path = "../aws-smithy-http" }
tower = { version = "0.4.4" }
pin-project = "1"
http = "0.2.3"
bytes = "1"
http-body = "0.4.0"
tracing = "0.1"

[dev-dependencies]
tower = { version = "0.4.4", features = ["util"] }
tokio = { version = "1", features = ["full"]}