[package]
name = "transcribestreaming_code_example"
version = "0.1.0"
authors = ["John DiSanti <jdisanti@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"
publish = false

[dependencies]
async-stream = "0.3"
bytes = "1"
hound = "3.4"

[dependencies.aws-config]
path = "../../sdk/aws-config"
version = "0.14.0"

[dependencies.aws-sdk-transcribestreaming]
path = "../../sdk/transcribestreaming"
version = "0.14.0"

[dependencies.structopt]
version = "0.3"
default-features = false

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.tracing-subscriber]
version = "0.3.5"
features = ["env-filter"]
