[package]
name = "sagemaker-code-examples"
version = "0.1.0"
authors = ["Alistair McLean <mclean@amazon.com>", "Doug Schwartz <dougsch@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { path = "../../aws-config" }
sagemaker = {package = "aws-sdk-sagemaker", path = "../../sagemaker"}
aws-types = { path = "../../aws-types" }

tokio = { version = "1", features = ["full"] }

env_logger = "0.8.2"
chrono = "0.4.19"
structopt = { version = "0.3", default-features = false }
tracing-subscriber = "0.2.18"
